In [1]:
import pandas as pd
import tensorflow as tf

In [2]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
physical_devices = tf.config.list_physical_devices('GPU')
try:
    tf.config.experimental.set_memory_growth(physical_devices[0], True)
except:
    pass

In [4]:
df= pd.read_csv("/Users/samriddhikumari/Desktop/College/symb/SEM_4/SML_prj/output/frame_features.csv")

In [5]:
df

frames  lbp_0  lbp_1  lbp_2  lbp_3  lbp_4  lbp_5  lbp_6  lbp_7  lbp_8  \
0     0001.jpg    218    330    275    583    873    751    516    431    437   
1     0002.jpg    218    330    275    583    873    751    516    431    437   
2     0003.jpg    218    330    275    583    873    751    516    431    437   
3     0004.jpg    218    330    275    583    873    751    516    431    437   
4     0005.jpg    218    330    275    583    873    751    516    431    437   
...        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
7565  7662.jpg    161    238    227    725   1430    975    332    243    256   
7566  7663.jpg    161    238    227    725   1430    975    332    243    256   
7567  7664.jpg    161    238    227    725   1430    975    332    243    256   
7568  7665.jpg    161    238    227    725   1430    975    332    243    256   
7569  7666.jpg    161    238    227    725   1430    975    332    243    256   

      ...  Lip_Feature_3  Lip_Feature_4  Lip_Feature_5  Lip_Feature_6  \
0     ...      13.152946     109.018347      43.104524      62.201286   
1     ...      22.022716     103.004854      45.044423      66.121101   
2     ...      20.000000     105.004762      45.044423      67.119297   
3     ...      23.000000     110.018180      43.046487      61.073726   
4     ...      21.000000     113.004425      43.046487      61.073726   
...   ...            ...            ...            ...            ...   
7565  ...      10.440307     164.878743      58.051701      88.119237   
7566  ...      14.317821     168.961534      58.694122      88.119237   
7567  ...       8.246211     172.742583      56.718604      85.988371   
7568  ...      12.165525     171.842952      57.706152      86.977008   
7569  ...       6.082763     174.928557      58.051701      87.965902   

      Lip_Feature_7  Lip_Feature_8  Lip_Feature_9  Lip_Feature_10  labels  \
0         62.072538      63.007936      43.046487      133.003759   जल्दी   
1         65.030762      66.000000      45.011110      127.003937   जल्दी   
2         66.030296      66.007575      44.011362      128.015624   जल्दी   
3         60.033324      61.000000      43.011626      132.034087   जल्दी   
4         60.008333      60.000000      42.011903      134.003731   जल्दी   
...             ...            ...            ...             ...     ...   
7565      81.498466      85.287748      57.078893      197.732142    करें   
7566      82.607506      86.284413      59.076222      203.887224    करें   
7567      80.504658      86.209048      58.034473      204.882893    करें   
7568      80.399005      85.146932      56.035703      204.882893    करें   
7569      80.504658      86.209048      58.077534      208.062491    करें   

         person  
0          agni  
1          agni  
2          agni  
3          agni  
4          agni  
...         ...  
7565  yasaswini  
7566  yasaswini  
7567  yasaswini  
7568  yasaswini  
7569  yasaswini  

[7570 rows x 76 columns]

In [6]:
df.columns

Index(['frames', 'lbp_0', 'lbp_1', 'lbp_2', 'lbp_3', 'lbp_4', 'lbp_5', 'lbp_6',
       'lbp_7', 'lbp_8', 'lbp_9', 'lbp_10', 'lbp_11', 'lbp_12', 'lbp_13',
       'lbp_14', 'lbp_15', 'lbp_16', 'lbp_17', 'lbp_18', 'lbp_19', 'lbp_20',
       'lbp_21', 'lbp_22', 'lbp_23', 'lbp_24', 'lbp_25', 'lbp_26', 'lbp_27',
       'lbp_28', 'lbp_29', 'lbp_30', 'lbp_31', 'lbp_32', 'lbp_33', 'lbp_34',
       'lbp_35', 'lbp_36', 'lbp_37', 'lbp_38', 'lbp_39', 'lbp_40', 'lbp_41',
       'lbp_42', 'lbp_43', 'lbp_44', 'lbp_45', 'lbp_46', 'lbp_47', 'lbp_48',
       'lbp_49', 'lbp_50', 'lbp_51', 'lbp_52', 'lbp_53', 'lbp_54', 'lbp_55',
       'lbp_56', 'lbp_57', 'lbp_58', 'optical_flow_0', 'optical_flow_1',
       'optical_flow_2', 'optical_flow_3', 'Lip_Feature_1', 'Lip_Feature_2',
       'Lip_Feature_3', 'Lip_Feature_4', 'Lip_Feature_5', 'Lip_Feature_6',
       'Lip_Feature_7', 'Lip_Feature_8', 'Lip_Feature_9', 'Lip_Feature_10',
       'labels', 'person'],
      dtype='object')

In [7]:
import pandas as pd

# Assuming df is your DataFrame

columns_to_drop = ['lbp_10', 'lbp_11', 'lbp_12', 'lbp_13', 'lbp_14', 'lbp_15', 'lbp_16', 'lbp_17', 'lbp_18', 'lbp_19', 'lbp_20', 'lbp_21', 'lbp_22', 'lbp_23', 'lbp_24', 'lbp_25', 'lbp_26', 'lbp_27', 'lbp_28', 'lbp_29', 'lbp_30', 'lbp_31', 'lbp_32', 'lbp_33', 'lbp_34', 'lbp_35', 'lbp_36', 'lbp_37', 'lbp_38', 'lbp_39', 'lbp_40', 'lbp_41', 'lbp_42', 'lbp_43', 'lbp_44', 'lbp_45', 'lbp_46', 'lbp_47', 'lbp_48', 'lbp_49', 'lbp_50', 'lbp_51', 'lbp_52', 'lbp_53', 'lbp_54', 'lbp_55', 'lbp_56', 'lbp_57', 'lbp_58']

df.drop(columns=columns_to_drop, inplace=True)


In [8]:
# Assuming df is your original DataFrame
df_without_missing_values = df.dropna()


In [9]:
df= df_without_missing_values

In [10]:
df.head(10)

frames  lbp_0  lbp_1  lbp_2  lbp_3  lbp_4  lbp_5  lbp_6  lbp_7  lbp_8  \
0  0001.jpg    218    330    275    583    873    751    516    431    437   
1  0002.jpg    218    330    275    583    873    751    516    431    437   
2  0003.jpg    218    330    275    583    873    751    516    431    437   
3  0004.jpg    218    330    275    583    873    751    516    431    437   
4  0005.jpg    218    330    275    583    873    751    516    431    437   
5  0006.jpg    218    330    275    583    873    751    516    431    437   
6  0007.jpg    218    330    275    583    873    751    516    431    437   
7  0008.jpg    218    330    275    583    873    751    516    431    437   
8  0009.jpg    218    330    275    583    873    751    516    431    437   
9  0010.jpg    218    330    275    583    873    751    516    431    437   

   ...  Lip_Feature_3  Lip_Feature_4  Lip_Feature_5  Lip_Feature_6  \
0  ...      13.152946     109.018347      43.104524      62.201286   
1  ...      22.022716     103.004854      45.044423      66.121101   
2  ...      20.000000     105.004762      45.044423      67.119297   
3  ...      23.000000     110.018180      43.046487      61.073726   
4  ...      21.000000     113.004425      43.046487      61.073726   
5  ...      20.000000     112.017856      42.047592      59.076222   
6  ...      21.000000     112.017856      42.011903      60.033324   
7  ...      23.000000     112.017856      43.046487      62.072538   
8  ...      22.022716     113.039816      43.046487      63.126856   
9  ...      21.023796     108.018517      44.045431      64.070274   

   Lip_Feature_7  Lip_Feature_8  Lip_Feature_9  Lip_Feature_10  labels  person  
0      62.072538      63.007936      43.046487      133.003759   जल्दी    agni  
1      65.030762      66.000000      45.011110      127.003937   जल्दी    agni  
2      66.030296      66.007575      44.011362      128.015624   जल्दी    agni  
3      60.033324      61.000000      43.011626      132.034087   जल्दी    agni  
4      60.008333      60.000000      42.011903      134.003731   जल्दी    agni  
5      58.034473      58.000000      40.012498      134.033578   जल्दी    agni  
6      60.008333      60.000000      41.012193      133.015037   जल्दी    agni  
7      61.032778      62.008064      42.047592      134.033578   जल्दी    agni  
8      62.072538      62.008064      42.011903      136.058811   जल्दी    agni  
9      62.032250      63.007936      43.011626      131.034347   जल्दी    agni  

[10 rows x 27 columns]

In [11]:
df.columns

Index(['frames', 'lbp_0', 'lbp_1', 'lbp_2', 'lbp_3', 'lbp_4', 'lbp_5', 'lbp_6',
       'lbp_7', 'lbp_8', 'lbp_9', 'optical_flow_0', 'optical_flow_1',
       'optical_flow_2', 'optical_flow_3', 'Lip_Feature_1', 'Lip_Feature_2',
       'Lip_Feature_3', 'Lip_Feature_4', 'Lip_Feature_5', 'Lip_Feature_6',
       'Lip_Feature_7', 'Lip_Feature_8', 'Lip_Feature_9', 'Lip_Feature_10',
       'labels', 'person'],
      dtype='object')

# Scaling

In [12]:
# Assuming df is your DataFrame containing lip features and labels
# Splitting the data into features and labels
from sklearn.model_selection import train_test_split
X = df.drop(columns=['frames', 'labels','person'])  # Assuming 'frames' is not a feature
y = df['labels']

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)


In [13]:
import pandas as pd

from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score


# Initialize the StandardScaler
scaler = StandardScaler()

# Fit and transform the training data
X_train_scaled = scaler.fit_transform(X_train)

# Transform the testing data
X_test_scaled = scaler.transform(X_test)

# Rf and ADA boost non-scaled

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score


# Initializing models
adaboost_dt = AdaBoostClassifier(n_estimators=20)  # AdaBoost with DecisionTreeClassifier as base estimator
random_forest = RandomForestClassifier(n_estimators=90)

# Training models
adaboost_dt.fit(X_train, y_train)
random_forest.fit(X_train, y_train)

# Making predictions
adaboost_dt_preds = adaboost_dt.predict(X_test)
random_forest_preds = random_forest.predict(X_test)a

# Evaluating models
adaboost_dt_accuracy = accuracy_score(y_test, adaboost_dt_preds)
random_forest_accuracy = accuracy_score(y_test, random_forest_preds)

print("AdaBoost with Decision Tree Base Accuracy:", adaboost_dt_accuracy)
print("Random Forest Accuracy:", random_forest_accuracy)


AdaBoost with Decision Tree Base Accuracy: 0.056672760511883
Random Forest Accuracy: 0.3304387568555759


# Rf and ADA boost scaled

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score


# Initializing models
adaboost_dt_scaled = AdaBoostClassifier(n_estimators=10)  # AdaBoost with DecisionTreeClassifier as base estimator
random_forest_scaled = RandomForestClassifier(n_estimators=100)
# Training models
adaboost_dt_scaled.fit(X_train_scaled, y_train)
random_forest_scaled.fit(X_train_scaled, y_train)

# Making predictions
adaboost_dt_preds = adaboost_dt_scaled.predict(X_test_scaled)
random_forest_preds = random_forest_scaled.predict(X_test_scaled)

# Evaluating models
adaboost_dt_accuracy = accuracy_score(y_test, adaboost_dt_preds)
random_forest_accuracy = accuracy_score(y_test, random_forest_preds)

print("AdaBoost with Decision Tree Base Accuracy:", adaboost_dt_accuracy)
print("Random Forest Accuracy:", random_forest_accuracy)


AdaBoost with Decision Tree Base Accuracy: 0.048446069469835464
Random Forest Accuracy: 0.3313528336380256


# Elbow plot for n_estimator for adaboost and rf

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.metrics import accuracy_score

# Define range of n_estimators
n_estimators_range = range(10, 121, 10)

# Initialize lists to store accuracies
adaboost_accuracies = []
random_forest_accuracies = []
adaboost_accuracies_scaled = []
random_forest_accuracies_scaled = []

# Iterate over n_estimators_range
for n_estimators in n_estimators_range:
    # Initialize models
    adaboost_dt = AdaBoostClassifier(n_estimators=n_estimators)  # AdaBoost with DecisionTreeClassifier as base estimator
    random_forest = RandomForestClassifier(n_estimators=n_estimators)
    adaboost_dt_scaled = AdaBoostClassifier(n_estimators=n_estimators)  # AdaBoost with DecisionTreeClassifier as base estimator
    random_forest_scaled = RandomForestClassifier(n_estimators=n_estimators)

    # Training models
    adaboost_dt.fit(X_train, y_train)
    random_forest.fit(X_train, y_train)

    # Making predictions
    adaboost_dt_preds = adaboost_dt.predict(X_test)
    random_forest_preds = random_forest.predict(X_test)
    
    # Training models scaled
    adaboost_dt_scaled.fit(X_train_scaled, y_train)
    random_forest_scaled.fit(X_train_scaled, y_train)

    # Making predictions scaled
    adaboost_dt_preds_scaled = adaboost_dt.predict(X_test_scaled)
    random_forest_preds_scaled = random_forest.predict(X_test_scaled)

    # Calculating accuracies
    adaboost_dt_accuracy = accuracy_score(y_test, adaboost_dt_preds)
    random_forest_accuracy = accuracy_score(y_test, random_forest_preds)
    adaboost_dt_accuracy_scaled = accuracy_score(y_test, adaboost_dt_preds_scaled)
    random_forest_accuracy_scaled = accuracy_score(y_test, random_forest_preds_scaled)

    # Append accuracies to lists
    adaboost_accuracies.append(adaboost_dt_accuracy)
    random_forest_accuracies.append(random_forest_accuracy)
    adaboost_accuracies_scaled.append(adaboost_dt_accuracy_scaled)
    random_forest_accuracies_scaled.append(random_forest_accuracy_scaled)

# Plotting elbow plot
plt.figure(figsize=(15, 5))

plt.subplot(1, 2, 1)
plt.plot(n_estimators_range, adaboost_accuracies, marker='o', linestyle='-')
plt.title('AdaBoost Accuracy vs. n_estimators')
plt.xlabel('n_estimators')
plt.ylabel('Accuracy')
plt.xticks(n_estimators_range)
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(n_estimators_range, random_forest_accuracies, marker='o', linestyle='-')
plt.title('Random Forest Accuracy vs. n_estimators')
plt.xlabel('n_estimators')
plt.ylabel('Accuracy')
plt.xticks(n_estimators_range)
plt.grid(True)

plt.tight_layout()
plt.show()


plt.figure(figsize=(15, 5))

plt.subplot(1, 2, 1)
plt.plot(n_estimators_range, adaboost_accuracies_scaled, marker='o', linestyle='-')
plt.title('AdaBoost Accuracy (Scaled) vs. n_estimators')
plt.xlabel('n_estimators')
plt.ylabel('Accuracy')
plt.xticks(n_estimators_range)
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(n_estimators_range, random_forest_accuracies_scaled, marker='o', linestyle='-')
plt.title('Random Forest Accuracy (Scaled) vs. n_estimators')
plt.xlabel('n_estimators')
plt.ylabel('Accuracy')
plt.xticks(n_estimators_range)
plt.grid(True)

# KNN (not and also Scaled)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

# Initialize k-NN classifier
knn_classifier = KNeighborsClassifier(n_neighbors=5)

# Train the classifier
knn_classifier.fit(X_train, y_train)

# Initialize k-NN classifier scaled
knn_classifier2 = KNeighborsClassifier(n_neighbors=5)

# Train the classifier scaled
knn_classifier2.fit(X_train_scaled, y_train)


KNeighborsClassifier()

# KNN elbow plot
## scaled and non

import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Define range of n_neighbors
n_neighbors_range = range(2, 12)

# Initialize a list to store accuracies
knn_accuracies = []
knn_accuracies_scaled = []

# Iterate over n_neighbors_range
for n_neighbors in n_neighbors_range:
    # Initialize k-NN classifier
    knn_classifier = KNeighborsClassifier(n_neighbors=n_neighbors)
    knn_classifier2 = KNeighborsClassifier(n_neighbors=n_neighbors)

    # Train the classifier
    knn_classifier.fit(X_train, y_train)
    knn_classifier2.fit(X_train_scaled, y_train)

    # Predict on test data
    knn_predictions = knn_classifier.predict(X_test)
    knn_predictions2 = knn_classifier2.predict(X_test_scaled)

    # Calculate accuracy
    knn_accuracy = accuracy_score(y_test, knn_predictions)
    knn_accuracy2 = accuracy_score(y_test, knn_predictions2)

    # Append accuracy to the list
    knn_accuracies.append(knn_accuracy)
    knn_accuracies_scaled.append(knn_accuracy2)

# Plotting elbow plot
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.plot(n_neighbors_range, knn_accuracies, marker='o', linestyle='-')
plt.title('k-NN Accuracy vs. n_neighbors')
plt.xlabel('n_neighbors')
plt.ylabel('Accuracy')
plt.xticks(n_neighbors_range)  # Corrected x-axis ticks
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(n_neighbors_range, knn_accuracies_scaled, marker='o', linestyle='-')
plt.title('k-NN Accuracy Scaled vs. n_neighbors')
plt.xlabel('n_neighbors')
plt.ylabel('Accuracy')
plt.xticks(n_neighbors_range)  # Corrected x-axis ticks
plt.grid(True)

plt.tight_layout()
plt.show()


import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Define range of n_neighbors
n_neighbors_range = range(2, 12)

# Initialize a list to store accuracies
knn_accuracies = []
knn_accuracies_scaled = []

# Iterate over n_neighbors_range
for n_neighbors in n_neighbors_range:
    # Initialize k-NN classifier
    knn_classifier = KNeighborsClassifier(n_neighbors=n_neighbors)
    knn_classifier2 = KNeighborsClassifier(n_neighbors=n_neighbors)

    # Train the classifier
    knn_classifier.fit(X_train, y_train)
    knn_classifier2.fit(X_train_scaled, y_train)

    # Predict on test data
    knn_predictions = knn_classifier.predict(X_test)
    knn_predictions2 = knn_classifier2.predict(X_test_scaled)

    # Calculate accuracy
    knn_accuracy = accuracy_score(y_test, knn_predictions)
    knn_accuracy2 = accuracy_score(y_test, knn_predictions2)

    # Append accuracy to the list
    knn_accuracies.append(knn_accuracy)
    knn_accuracies_scaled.append(knn_accuracy2)

# Plotting elbow plot
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.plot(n_neighbors_range, knn_accuracies, marker='o', linestyle='-')
plt.title('k-NN Accuracy vs. n_neighbors')
plt.xlabel('n_neighbors')
plt.ylabel('Accuracy')
plt.xticks(np.arange(min(n_neighbors_range), max(n_neighbors_range)+1, 10))
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(n_neighbors_range, knn_accuracies_scaled, marker='o', linestyle='-')
plt.title('k-NN Accuracy Scaled vs. n_neighbors')
plt.xlabel('n_neighbors')
plt.ylabel('Accuracy')
plt.xticks(np.arange(min(n_neighbors_range), max(n_neighbors_range)+1, 10))
plt.grid(True)

plt.tight_layout()
plt.show()


# Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression

# Initialize Logistic Regression classifier
logreg_classifier = LogisticRegression(max_iter=1000)

# Train the classifier
logreg_classifier.fit(X_train_scaled, y_train)

# Predict on test data
logreg_predictions = logreg_classifier.predict(X_test_scaled)


# GradientBoostingClassifier

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

# Initialize Gradient Boosting classifier
gbm_classifier = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1)

# Train the classifier
gbm_classifier.fit(X_train_scaled, y_train)

# Predict on test data
gbm_predictions = gbm_classifier.predict(X_test_scaled)


In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# k-Nearest Neighbors (k-NN)
knn_predictions = knn_classifier.predict(X_test_scaled)
knn_accuracy = accuracy_score(y_test, knn_predictions)
knn_precision = precision_score(y_test, knn_predictions, average='weighted')
knn_recall = recall_score(y_test, knn_predictions, average='weighted')
knn_f1 = f1_score(y_test, knn_predictions, average='weighted')
knn_conf_matrix = confusion_matrix(y_test, knn_predictions)

print("k-Nearest Neighbors (k-NN) Metrics:")
print("Accuracy:", knn_accuracy)
print("Precision:", knn_precision)
print("Recall:", knn_recall)
print("F1-score:", knn_f1)
print("Confusion Matrix:")
print(knn_conf_matrix)
print("\n")

# k-Nearest Neighbors (k-NN)
knn_predictions = knn_classifier2.predict(X_test_scaled)
knn_accuracy = accuracy_score(y_test, knn_predictions)
knn_precision = precision_score(y_test, knn_predictions, average='weighted')
knn_recall = recall_score(y_test, knn_predictions, average='weighted')
knn_f1 = f1_score(y_test, knn_predictions, average='weighted')
knn_conf_matrix = confusion_matrix(y_test, knn_predictions)

print("k-Nearest Neighbors (k-NN) Metrics Scaled:")
print("Accuracy:", knn_accuracy)
print("Precision:", knn_precision)
print("Recall:", knn_recall)
print("F1-score:", knn_f1)
print("Confusion Matrix:")
print(knn_conf_matrix)
print("\n")

# Logistic Regression
logreg_predictions = logreg_classifier.predict(X_test)
logreg_accuracy = accuracy_score(y_test, logreg_predictions)
logreg_precision = precision_score(y_test, logreg_predictions, average='weighted')
logreg_recall = recall_score(y_test, logreg_predictions, average='weighted')
logreg_f1 = f1_score(y_test, logreg_predictions, average='weighted')
logreg_conf_matrix = confusion_matrix(y_test, logreg_predictions)

print("Logistic Regression Metrics:")
print("Accuracy:", logreg_accuracy)
print("Precision:", logreg_precision)
print("Recall:", logreg_recall)
print("F1-score:", logreg_f1)
print("Confusion Matrix:")
print(logreg_conf_matrix)
print("\n")

# Gradient Boosting Machines (GBM)
gbm_predictions = gbm_classifier.predict(X_test)
gbm_accuracy = accuracy_score(y_test, gbm_predictions)
gbm_precision = precision_score(y_test, gbm_predictions, average='weighted')
gbm_recall = recall_score(y_test, gbm_predictions, average='weighted')
gbm_f1 = f1_score(y_test, gbm_predictions, average='weighted')
gbm_conf_matrix = confusion_matrix(y_test, gbm_predictions)

print("Gradient Boosting Machines (GBM) Metrics:")
print("Accuracy:", gbm_accuracy)
print("Precision:", gbm_precision)
print("Recall:", gbm_recall)
print("F1-score:", gbm_f1)
print("Confusion Matrix:")
print(gbm_conf_matrix)
print("\n")


/home/student/anaconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
/home/student/anaconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/student/anaconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


k-Nearest Neighbors (k-NN) Metrics:
Accuracy: 0.005941499085923218
Precision: 3.5301411388026434e-05
Recall: 0.005941499085923218
F1-score: 7.018581382735286e-05
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


k-Nearest Neighbors (k-NN) Metrics Scaled:
Accuracy: 0.23217550274223034
Precision: 0.24802236826622517
Recall: 0.23217550274223034
F1-score: 0.2217023468260938
Confusion Matrix:
[[12  0  0 ...  0  0  0]
 [ 0  6  0 ...  0  0  0]
 [ 0  0  0 ...  0  1  0]
 ...
 [ 0  0  0 ...  1  0  0]
 [ 2  2  0 ...  2 26  0]
 [ 0  0  0 ...  0  0  0]]


Logistic Regression Metrics:
Accuracy: 0.012340036563071298
Precision: 0.0017222693450864514
Recall: 0.012340036563071298
F1-score: 0.002095168987353604
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]




/home/student/anaconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/home/student/anaconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/student/anaconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but GradientBoostingClassifier was fitted without feature names
  warnings.warn(


Gradient Boosting Machines (GBM) Metrics:
Accuracy: 0.002742230347349177
Precision: 7.692090735902321e-06
Recall: 0.002742230347349177
F1-score: 1.534114879635903e-05
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]




/home/student/anaconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Random forest and SVC Tuned

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Assuming you have X_train_scaled, X_test_scaled, y_train, and y_test defined somewhere

# Define the parameter grid to search
param_grid_rf = {
    'n_estimators': [50, 100, 150],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Initialize Random Forest classifier
rf_classifier_gs = RandomForestClassifier()

# Initialize GridSearchCV
grid_search_rf = GridSearchCV(estimator=rf_classifier_gs, param_grid=param_grid_rf, cv=5, n_jobs=-1, scoring='accuracy')

# Perform grid search to find the best parameters
grid_search_rf.fit(X_train_scaled, y_train)

# Get the best parameters and best estimator
best_params_rf = grid_search_rf.best_params_
best_estimator_rf = grid_search_rf.best_estimator_

# Make predictions using the best estimator
best_preds_rf = best_estimator_rf.predict(X_test_scaled)

# Calculate accuracy using the best estimator
best_accuracy_rf = accuracy_score(y_test, best_preds_rf)

print("Best Parameters:", best_params_rf)
print("Best Accuracy:", best_accuracy_rf)





/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/joblib/externals/loky/backend/fork_exec.py:38: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid = os.fork()
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/joblib/externals/loky/backend/fork_exec.py:38: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid = os.fork()
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(


Best Parameters: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 150}
Best Accuracy: 0.3381770145310436


In [15]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# Calculate and print the testing accuracy using the best estimator
best_accuracy_rf = accuracy_score(y_test, best_preds_rf)
print("Best Accuracy:", best_accuracy_rf)

# Calculate precision, recall, and F1 score using weighted averages
precision = precision_score(y_test, best_preds_rf, average='weighted')
recall = recall_score(y_test, best_preds_rf, average='weighted')
f1 = f1_score(y_test, best_preds_rf, average='weighted')

# Print the metrics
print("Best Random Forest Precision:", precision)
print("Best Random Forest Recall:", recall)
print("Best Random Forest F1 Score:", f1)

# Optionally, print a classification report for more detailed evaluation
print("\nClassification Report for Best Random Forest:")
print(classification_report(y_test, best_preds_rf, zero_division=1))


Best Accuracy: 0.3381770145310436
Best Random Forest Precision: 0.3410516822120467
Best Random Forest Recall: 0.3381770145310436
Best Random Forest F1 Score: 0.3254574828577433

Classification Report for Best Random Forest:
              precision    recall  f1-score   support

    आवश्यकता       0.39      0.52      0.45        21
       आसमान       0.89      0.47      0.62        17
         उड़       0.29      0.33      0.31         6
         उतर       0.60      0.46      0.52        13
        ऊंची       0.62      0.42      0.50        19
          एक       0.33      0.18      0.24        11
          कप       0.00      0.00      0.00         6
          कर       0.38      0.33      0.35         9
        करते       0.69      0.69      0.69        16
        करने       0.00      0.00      0.00         6
        करें       0.58      0.50      0.54        30
          का       0.35      0.53      0.42        15
       कागज़       0.23      0.33      0.27         9
         काट       

In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Assuming you have X_train_scaled, X_test_scaled, y_train, and y_test defined somewhere

# Define the parameter grid to search
param_grid_svc = {
    'C': [0.1, 1, 10],             # Regularization parameter
    'kernel': ['linear', 'rbf','sigmoid','poly'],   # Kernel type
    'gamma': ['scale', 'auto']     # Kernel coefficient for 'rbf' kernel
}

# Initialize SVC model
svc_gs = SVC()

# Initialize GridSearchCV
grid_search_svc = GridSearchCV(estimator=svc_gs, param_grid=param_grid_svc, cv=5, n_jobs=-1, scoring='accuracy')

# Perform grid search to find the best parameters
grid_search_svc.fit(X_train_scaled, y_train)

# Get the best parameters and best estimator
best_params_svc = grid_search_svc.best_params_
best_estimator_svc = grid_search_svc.best_estimator_

# Make predictions using the best estimator
best_preds_svc = best_estimator_svc.predict(X_test_scaled)

# Calculate accuracy using the best estimator
best_accuracy_svc = accuracy_score(y_test, best_preds_svc)

print("Best Parameters:", best_params_svc)
print("Best Accuracy:", best_accuracy_svc)


Best Parameters: {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}
Best Accuracy: 0.2712461470717745


In [19]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# Make predictions on the training and testing sets using the best estimator from grid search
train_preds_svc = best_estimator_svc.predict(X_train_scaled)
test_preds_svc = best_estimator_svc.predict(X_test_scaled)

# Calculate training and testing accuracy
train_accuracy_svc = accuracy_score(y_train, train_preds_svc)
test_accuracy_svc = accuracy_score(y_test, test_preds_svc)

# Calculate precision, recall, and F1 score (using weighted average) on the testing set
precision_svc = precision_score(y_test, test_preds_svc, average='weighted')
recall_svc = recall_score(y_test, test_preds_svc, average='weighted')
f1_svc = f1_score(y_test, test_preds_svc, average='weighted')

# Print results
print("SVC:")
print(f"Training Accuracy: {train_accuracy_svc}")
print(f"Testing Accuracy: {test_accuracy_svc}")
print(f"Weighted Precision: {precision_svc}")
print(f"Weighted Recall: {recall_svc}")
print(f"Weighted F1 Score: {f1_svc}")

# Optionally, you can print a classification report to get a more detailed evaluation
print("\nClassification Report for SVC:")
print(classification_report(y_test, test_preds_svc))


SVC:
Training Accuracy: 0.4792296072507553
Testing Accuracy: 0.2712461470717745
Weighted Precision: 0.2752062156053166
Weighted Recall: 0.2712461470717745
Weighted F1 Score: 0.25486502015879764

Classification Report for SVC:
              precision    recall  f1-score   support

    आवश्यकता       0.28      0.48      0.35        21
       आसमान       0.75      0.35      0.48        17
         उड़       0.10      0.17      0.12         6
         उतर       0.25      0.38      0.30        13
        ऊंची       0.50      0.32      0.39        19
          एक       0.20      0.09      0.12        11
          कप       0.00      0.00      0.00         6
          कर       0.50      0.22      0.31         9
        करते       0.53      0.50      0.52        16
        करने       0.10      0.33      0.15         6
        करें       0.33      0.40      0.36        30
          का       0.33      0.20      0.25        15
       कागज़       0.09      0.22      0.13         9
         काट     

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  

In [ ]:
import joblib

# Save k-Nearest Neighbors (k-NN) model
joblib.dump(knn_classifier, 'knn_model.pkl')

# Save k-Nearest Neighbors (k-NN) model
joblib.dump(knn_classifier2, 'knn_model2.pkl')

# Save Logistic Regression model
joblib.dump(logreg_classifier, 'logreg_model.pkl')

# Save Gradient Boosting Machines (GBM) model
joblib.dump(gbm_classifier, 'gbm_model.pkl')

# Save AdaBoost with Decision Tree Base model
joblib.dump(adaboost_dt, 'adaboost_dt_model.pkl')

# Save AdaBoost with Decision Tree Base model
joblib.dump(adaboost_dt_scaled, 'adaboost_dt_scaled_model.pkl')

# Save Random Forest model
joblib.dump(random_forest, 'random_forest_model.pkl')

# Save Random Forest model
joblib.dump(random_forest_scaled, 'random_forest_scaled_model.pkl')


['random_forest_scaled_model.pkl']

In [ ]:
import joblib

# Save the best RandomForestClassifier model
joblib.dump(best_estimator_rf, 'best_random_forest_model.pkl')

# Save the best SVC model
joblib.dump(best_estimator_svc, 'best_svc_model.pkl')

# Save the best SVC model
joblib.dump(svc_gs, 'svc_gs_model.pkl')


# Assuming you used StandardScaler
joblib.dump(scaler, 'scaler.pkl')



In [ ]:

# Save the best RandomForestClassifier model
joblib.dump(rf_classifier_gs, 'random_forest_gs_model.pkl')

['random_forest_gs_model.pkl']